# Generated by Django 3.2.9 on 2021-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=300)),
                ('expires_in', models.CharField(max_length=80)),
                ('token_type', models.CharField(max_length=80)),
            ],
        ),
    ]
